In [1]:
#QUESTION 3:
my_dna = "ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT"
length = len(my_dna)
a_count = my_dna.count('A')
t_count = my_dna.count('T')
print("length: " + str(length))
print("A count: " + str(a_count))
print("T count: " + str(t_count))



length: 54
A count: 16
T count: 21


In [3]:
test_dna = "ATGC"
length = len(test_dna)
a_count = test_dna.count('A')
t_count = test_dna.count('T')
print("length: " + str(length))
print("A count: " + str(a_count))
print("T count: " + str(t_count))

length: 4
A count: 1
T count: 1


In [4]:
test_dna = "ATGC"
length = len(test_dna)
a_count = test_dna.count('A')
t_count = test_dna.count('T')
at_content = a_count + t_count / length
print("AT content is " + str(at_content))

AT content is 1.25


In [6]:
test_dna = "ATGC"
length = len(test_dna)
a_count = test_dna.count('A')
t_count = test_dna.count('T')
at_content = (a_count + t_count) / length
print("AT content is " + str(at_content))

AT content is 0.5


In [7]:
my_dna = "ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT"
length = len(my_dna)
a_count = my_dna.count('A')
t_count = my_dna.count('T')
at_content = (a_count + t_count) / length
print("AT content is " + str(at_content))

AT content is 0.6851851851851852


In [8]:
#QUESTION 4:

#1)check your understanding:done
#2)sorting out referances:
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)

Hopper Grace


In [14]:
#3)slicing strings:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [31]:
element = 'oxygen'
print('first three characters:', element[0:4])
print('last two characters:', element[4:6])
print('full word:', element[:])

first three characters: oxyg
last two characters: en
full word: oxygen


In [35]:
element = 'oxygen'
print('last characters:', element[-1])
print('last characters:', element[-2])
#Creates a substring from index 1 up to (not including)
#the final index, effectively removing the first and last 
#letters from ‘oxygen’

last characters: n
last characters: e


In [85]:
#4)Thin slices:
element = 'oxygen'
print('the expression element:', element[3:3])
print('the expression element:', element[3:3, 4:4])
print('the expression element:', element[3:3, :])

the expression element: 


TypeError: string indices must be integers

In [89]:
#5)plot scaling:
#Because matplotlib normally sets x and y axes limits to the min and max of our data (depending on data range)
def axes3 = ("plot")
axes3.set_ylabel('min')
axes3.plot(numpy.min(data, axis=0))
axes3.set_ylim(0,6)

SyntaxError: invalid syntax (<ipython-input-89-1a32db211c7b>, line 3)

In [98]:
#6)Drawing straight lines:
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(numpy.mean(data, axis=0), drawstyle='steps-mid')

axes2.set_ylabel('max')
axes2.plot(numpy.max(data, axis=0), drawstyle='steps-mid')

axes3.set_ylabel('min')
axes3.plot(numpy.min(data, axis=0), drawstyle='steps-mid')

fig.tight_layout()

matplotlib.pyplot.show()

FileNotFoundError: [Errno 2] No such file or directory: 'inflammation-01.csv'

In [94]:
#7)Make you own plot:
max_plot = matplotlib.pyplot.plot(numpy.std(data, axis=0))
matplotlib.pyplot.show()

NameError: name 'data' is not defined

In [97]:
#8)moving things around:

import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')


fig = matplotlib.pyplot.figure(figsize=(3.0, 10.0))

axes1 = fig.add_subplot(3, 1, 1)
axes2 = fig.add_subplot(3, 1, 2)
axes3 = fig.add_subplot(3, 1, 3)

axes1.set_ylabel('average')
axes1.plot(numpy.mean(data, axis=0))

axes2.set_ylabel('max')
axes2.plot(numpy.max(data, axis=0))

axes3.set_ylabel('min')
axes3.plot(numpy.min(data, axis=0))

fig.tight_layout()

matplotlib.pyplot.show()

FileNotFoundError: [Errno 2] No such file or directory: 'data/inflammation-01.csv'

In [76]:
#9)Stacking Arrays:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
D = numpy.hstack((A[:, :1], A[:, -1:]))
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [78]:
D = numpy.delete(A, 1, 1)
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]
